name: Lores
main: com.codisimus.plugins.lores.Lores
version: 1.2.0
author: Codisimus
website: www.codisimus.com
description: Modify Item names and lores
commands:
  lore:
    description: Main command for the plugin
permissions:
  lores.lore:
    default: false
  lores.name:
    default: false
  lores.owner:
    default: false
  lores.color:
    default: false
  lores.format:
    default: false
  lores.admin:
    default: op
    children:
      lores.lore: true
      lores.name: true
      lores.owner: true
      lores.color: true
      lores.format: true